title:             Curso de Python en Río Cuarto
email:             bibiana.rivadeneira@gmail.com
description:       Primera edición del curso de introducción a Python en Río Cuarto.
author:            Bibiana

# Social Profiles
twitter_username:  3ibiana
github_username:   brivadeneira
facebook_username:
google_analytics: UA-139349099-1 # Google Analytics id, e.g. "UA-NNNNNNNN-N
